CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260603123813_InitialIdentity', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE case_enclosure (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "FormFactorSupport" character varying(50) NOT NULL,
    "MaxVGALength" integer NOT NULL,
    "Color" character varying(30),
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_case_enclosure" PRIMARY KEY ("Id")
);

CREATE TABLE cpu (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "Socket" character varying(50) NOT NULL,
    "CoreCount" integer NOT NULL,
    "ThreadCount" integer NOT NULL,
    "BaseClock" numeric(5,2) NOT NULL,
    "BoostClock" numeric(5,2) NOT NULL,
    "TDP" integer NOT NULL,
    "ApproximatePerformance" numeric(10,2) NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_cpu" PRIMARY KEY ("Id")
);

CREATE TABLE cpu_cooler (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "SocketCompatibility" character varying(200) NOT NULL,
    "MaxTDP" integer NOT NULL,
    "Height" integer NOT NULL,
    "Type" character varying(30) NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_cpu_cooler" PRIMARY KEY ("Id")
);

CREATE TABLE memory (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "Type" character varying(10) NOT NULL,
    "Capacity" integer NOT NULL,
    "Modules" integer NOT NULL,
    "Speed" integer NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_memory" PRIMARY KEY ("Id")
);

CREATE TABLE motherboard (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "SocketCompatibility" character varying(50) NOT NULL,
    "FormFactor" character varying(20) NOT NULL,
    "MemoryCompatibility" character varying(10) NOT NULL,
    "MemorySlots" integer NOT NULL,
    "MaxMemoryCapacity" integer NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_motherboard" PRIMARY KEY ("Id")
);

CREATE TABLE power_supply (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "Wattage" integer NOT NULL,
    "Efficiency" character varying(30) NOT NULL,
    "Modular" character varying(20) NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_power_supply" PRIMARY KEY ("Id")
);

CREATE TABLE storage (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "Type" character varying(20) NOT NULL,
    "Capacity" integer NOT NULL,
    "Interface" character varying(20) NOT NULL,
    "ReadSpeed" integer NOT NULL,
    "WriteSpeed" integer NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_storage" PRIMARY KEY ("Id")
);

CREATE TABLE video_card (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Manufacturer" character varying(100) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "VRAM" integer NOT NULL,
    "Length" integer NOT NULL,
    "TDP" integer NOT NULL,
    "ApproximatePerformance" numeric(10,2) NOT NULL,
    "ImageUrl" text,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_video_card" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260603130850_HardwareSchema', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE carts (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_carts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_carts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE orders (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "TotalAmount" numeric(18,0) NOT NULL,
    "Status" integer NOT NULL,
    "RecipientName" character varying(200) NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "ShippingAddress" character varying(500) NOT NULL,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE cart_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CartId" integer NOT NULL,
    "Category" character varying(50) NOT NULL,
    "ComponentId" integer NOT NULL,
    "ComponentName" character varying(300) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "Quantity" integer NOT NULL,
    "ImageUrl" text,
    CONSTRAINT "PK_cart_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_cart_items_carts_CartId" FOREIGN KEY ("CartId") REFERENCES carts ("Id") ON DELETE CASCADE
);

CREATE TABLE order_details (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Category" character varying(50) NOT NULL,
    "ComponentId" integer NOT NULL,
    "ComponentName" character varying(300) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "Quantity" integer NOT NULL,
    "ImageUrl" text,
    CONSTRAINT "PK_order_details" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_order_details_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_cart_items_CartId" ON cart_items ("CartId");

CREATE INDEX "IX_carts_UserId" ON carts ("UserId");

CREATE INDEX "IX_order_details_OrderId" ON order_details ("OrderId");

CREATE INDEX "IX_orders_UserId" ON orders ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260604120341_AddCartAndOrders', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE saved_builds (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Name" character varying(100) NOT NULL,
    "BuildJson" text NOT NULL,
    "ShareToken" character varying(32) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_saved_builds" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_saved_builds_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_saved_builds_UserId" ON saved_builds ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260606101426_AddSavedBuilds', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260606143447_AddDataProtectionKeys', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE saved_builds ADD "IsPublic" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE saved_builds ADD "UpvoteCount" integer NOT NULL DEFAULT 0;

CREATE TABLE build_upvotes (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BuildId" integer NOT NULL,
    "UserId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_build_upvotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_build_upvotes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_build_upvotes_saved_builds_BuildId" FOREIGN KEY ("BuildId") REFERENCES saved_builds ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_build_upvotes_BuildId_UserId" ON build_upvotes ("BuildId", "UserId");

CREATE INDEX "IX_build_upvotes_UserId" ON build_upvotes ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607085223_AddBuildCommunity', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE price_history (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" character varying(30) NOT NULL,
    "ProductName" character varying(200) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "RecordedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_price_history" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_price_history_Category_ProductName_RecordedAt" ON price_history ("Category", "ProductName", "RecordedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607085541_AddPriceHistory', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE wishlist_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Category" character varying(50) NOT NULL,
    "ComponentId" integer NOT NULL,
    "ComponentName" character varying(300) NOT NULL,
    "Price" numeric(18,0) NOT NULL,
    "ImageUrl" text,
    "AddedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_wishlist_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_wishlist_items_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_wishlist_items_UserId_Category_ComponentId" ON wishlist_items ("UserId", "Category", "ComponentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607085821_AddWishlist', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE power_supply ADD "PsuFormFactor" character varying(10) NOT NULL DEFAULT '';

ALTER TABLE motherboard ADD "Chipset" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE memory ADD "Profile" character varying(30) NOT NULL DEFAULT '';

ALTER TABLE case_enclosure ADD "CaseType" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE case_enclosure ADD "RadiatorSupport" character varying(50) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607143420_AddFilterFields', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE product_questions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Category" character varying(50) NOT NULL,
    "ComponentId" integer NOT NULL,
    "Question" character varying(500) NOT NULL,
    "UserDisplayName" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_product_questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_product_questions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE product_reviews (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Category" character varying(50) NOT NULL,
    "ComponentId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(1000),
    "UserDisplayName" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_product_reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_product_reviews_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE product_answers (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Answer" character varying(1000) NOT NULL,
    "UserDisplayName" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_product_answers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_product_answers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_product_answers_product_questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES product_questions ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_product_answers_QuestionId" ON product_answers ("QuestionId");

CREATE INDEX "IX_product_answers_UserId" ON product_answers ("UserId");

CREATE INDEX "IX_product_questions_Category_ComponentId" ON product_questions ("Category", "ComponentId");

CREATE INDEX "IX_product_questions_UserId" ON product_questions ("UserId");

CREATE INDEX "IX_product_reviews_Category_ComponentId" ON product_reviews ("Category", "ComponentId");

CREATE UNIQUE INDEX "IX_product_reviews_UserId_Category_ComponentId" ON product_reviews ("UserId", "Category", "ComponentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607160155_AddReviewsAndQA', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE warranty_records (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer,
    "Phone" character varying(20),
    "ProductName" character varying(300) NOT NULL,
    "Category" character varying(50) NOT NULL,
    "ComponentId" integer NOT NULL,
    "ImageUrl" text,
    "PurchaseDate" timestamp with time zone NOT NULL,
    "WarrantyMonths" integer NOT NULL,
    "SerialNumber" character varying(100),
    CONSTRAINT "PK_warranty_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_warranty_records_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("Id")
);

CREATE INDEX "IX_warranty_records_OrderId" ON warranty_records ("OrderId");

CREATE INDEX "IX_warranty_records_Phone" ON warranty_records ("Phone");

CREATE INDEX "IX_warranty_records_SerialNumber" ON warranty_records ("SerialNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607161515_AddWarrantyRecords', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE orders ADD "DiscountAmount" numeric(18,0) NOT NULL DEFAULT 0.0;

ALTER TABLE orders ADD "PaymentMethod" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607162145_AddPaymentMethodAndDiscount', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE video_card ADD "StockStatusOverride" integer;

ALTER TABLE storage ADD "StockStatusOverride" integer;

ALTER TABLE power_supply ADD "StockStatusOverride" integer;

ALTER TABLE motherboard ADD "StockStatusOverride" integer;

ALTER TABLE memory ADD "StockStatusOverride" integer;

ALTER TABLE cpu_cooler ADD "StockStatusOverride" integer;

ALTER TABLE cpu ADD "StockStatusOverride" integer;

ALTER TABLE case_enclosure ADD "StockStatusOverride" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607165135_AddStockStatusOverride', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE video_card ADD "VideoUrl" text;

ALTER TABLE storage ADD "VideoUrl" text;

ALTER TABLE power_supply ADD "VideoUrl" text;

ALTER TABLE motherboard ADD "VideoUrl" text;

ALTER TABLE memory ADD "VideoUrl" text;

ALTER TABLE cpu_cooler ADD "VideoUrl" text;

ALTER TABLE cpu ADD "VideoUrl" text;

ALTER TABLE case_enclosure ADD "VideoUrl" text;

CREATE TABLE coupons (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Description" character varying(200),
    "DiscountType" integer NOT NULL,
    "DiscountValue" numeric(18,2) NOT NULL,
    "MinOrderAmount" numeric(18,2),
    "MaxUses" integer,
    "UsedCount" integer NOT NULL,
    "CategoryFilter" character varying(200),
    "BrandFilter" character varying(100),
    "IsFreeShip" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "StartsAt" timestamp with time zone,
    "ExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_coupons" PRIMARY KEY ("Id")
);

CREATE TABLE flash_sales (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" character varying(20) NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductName" character varying(300) NOT NULL,
    "OriginalPrice" numeric(18,2) NOT NULL,
    "DiscountPercent" integer NOT NULL,
    "SalePrice" numeric(18,2) NOT NULL,
    "TotalQty" integer NOT NULL,
    "SoldQty" integer NOT NULL,
    "StartsAt" timestamp with time zone NOT NULL,
    "EndsAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_flash_sales" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607221800_AddFlashSaleAndCoupon', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUsers" ADD "LoyaltyPoints" integer NOT NULL DEFAULT 0;

ALTER TABLE "AspNetUsers" ADD "TotalSpend" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607223228_AddLoyaltyFields', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE bundles (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500),
    "DiscountPercent" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_bundles" PRIMARY KEY ("Id")
);

CREATE TABLE bundle_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BundleId" integer NOT NULL,
    "Category" character varying(20) NOT NULL,
    "ComponentId" integer NOT NULL,
    "ProductName" character varying(300) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_bundle_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_bundle_items_bundles_BundleId" FOREIGN KEY ("BundleId") REFERENCES bundles ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_bundle_items_BundleId" ON bundle_items ("BundleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607223417_AddBundles', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE product_reviews ADD "ImageUrl" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607223826_AddReviewImageUrl', '8.0.0');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_product_reviews_UserId_Category_ComponentId";

CREATE INDEX "IX_product_reviews_UserId" ON product_reviews ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260607230519_AllowMultipleReviews', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE component_benchmarks (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" character varying(20) NOT NULL,
    "ComponentName" character varying(200) NOT NULL,
    "CinebenchR23Multi" integer,
    "CinebenchR23Single" integer,
    "FpsCs2_1080p" integer,
    "FpsCs2_1440p" integer,
    "FpsCyberpunk_1080p" integer,
    "FpsCyberpunk_1440p" integer,
    "FpsValorant_1080p" integer,
    "FpsValorant_1440p" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_component_benchmarks" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260608011459_AddComponentBenchmarks', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE quote_requests (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PhoneOrEmail" character varying(200) NOT NULL,
    "Budget" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsContacted" boolean NOT NULL,
    CONSTRAINT "PK_quote_requests" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260608163752_AddQuoteRequests', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE video_card ADD "SourceUrl" text;

ALTER TABLE storage ADD "SourceUrl" text;

ALTER TABLE power_supply ADD "SourceUrl" text;

ALTER TABLE motherboard ADD "SourceUrl" text;

ALTER TABLE memory ADD "SourceUrl" text;

ALTER TABLE cpu_cooler ADD "SourceUrl" text;

ALTER TABLE cpu ADD "SourceUrl" text;

ALTER TABLE case_enclosure ADD "SourceUrl" text;

CREATE TABLE product_articles (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductCategory" character varying(20),
    "ProductId" integer,
    "Source" character varying(20) NOT NULL,
    "Url" text NOT NULL,
    "Title" text NOT NULL,
    "Content" text,
    "ThumbnailUrl" text,
    "PublishedAt" timestamp with time zone,
    "ScrapedAt" timestamp with time zone NOT NULL,
    "MatchScore" double precision,
    CONSTRAINT "PK_product_articles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_product_articles_Url" ON product_articles ("Url");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260613235321_AddSourceUrlToHardwareTables', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260613235333_AddProductArticles', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE video_card ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);

ALTER TABLE cpu ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260615173549_AddCreatedAtToCpuAndVideoCard', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE saved_builds DROP CONSTRAINT "FK_saved_builds_AspNetUsers_UserId";

ALTER TABLE saved_builds ALTER COLUMN "UserId" DROP NOT NULL;

ALTER TABLE saved_builds ADD "ExpiresAt" timestamp with time zone;

ALTER TABLE saved_builds ADD "IsAnonymous" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE saved_builds ADD CONSTRAINT "FK_saved_builds_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260615190128_AddAnonymousShare', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE prebuilt_pcs (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Purpose" character varying(100),
    "Price" numeric NOT NULL,
    "OldPrice" numeric,
    "ImageUrl" character varying(500),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CpuId" integer,
    "MotherboardId" integer,
    "MemoryId" integer,
    "VideoCardId" integer,
    "StorageId" integer,
    "PowerSupplyId" integer,
    "CaseId" integer,
    "CoolerId" integer,
    CONSTRAINT "PK_prebuilt_pcs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_case_enclosure_CaseId" FOREIGN KEY ("CaseId") REFERENCES case_enclosure ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_cpu_CpuId" FOREIGN KEY ("CpuId") REFERENCES cpu ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_cpu_cooler_CoolerId" FOREIGN KEY ("CoolerId") REFERENCES cpu_cooler ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_memory_MemoryId" FOREIGN KEY ("MemoryId") REFERENCES memory ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_motherboard_MotherboardId" FOREIGN KEY ("MotherboardId") REFERENCES motherboard ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_power_supply_PowerSupplyId" FOREIGN KEY ("PowerSupplyId") REFERENCES power_supply ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_storage_StorageId" FOREIGN KEY ("StorageId") REFERENCES storage ("Id"),
    CONSTRAINT "FK_prebuilt_pcs_video_card_VideoCardId" FOREIGN KEY ("VideoCardId") REFERENCES video_card ("Id")
);

CREATE INDEX "IX_prebuilt_pcs_CaseId" ON prebuilt_pcs ("CaseId");

CREATE INDEX "IX_prebuilt_pcs_CoolerId" ON prebuilt_pcs ("CoolerId");

CREATE INDEX "IX_prebuilt_pcs_CpuId" ON prebuilt_pcs ("CpuId");

CREATE INDEX "IX_prebuilt_pcs_MemoryId" ON prebuilt_pcs ("MemoryId");

CREATE INDEX "IX_prebuilt_pcs_MotherboardId" ON prebuilt_pcs ("MotherboardId");

CREATE INDEX "IX_prebuilt_pcs_PowerSupplyId" ON prebuilt_pcs ("PowerSupplyId");

CREATE INDEX "IX_prebuilt_pcs_StorageId" ON prebuilt_pcs ("StorageId");

CREATE INDEX "IX_prebuilt_pcs_VideoCardId" ON prebuilt_pcs ("VideoCardId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260616151549_AddPrebuiltPcs', '8.0.0');

COMMIT;

